# Day 14, 15 - Assignment

# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
m_3D = np.empty((3,3,3))
print(m_3D)

[[[1.39047140e-311 1.39047110e-311 9.08367206e+223]
  [1.47372294e+195 7.36099718e+223 2.12601662e+121]
  [3.07666482e+262 3.54039281e-057 4.45384947e-033]]

 [[5.08100980e+233 8.40217694e+217 6.88492102e-085]
  [3.09775430e-080 2.66104499e-260 7.48960144e+247]
  [4.47593816e-091 3.74168656e+233 6.17469411e-114]]

 [[1.69264133e-139 3.42630849e-086 7.12605658e-067]
  [1.52059452e-047 5.28595595e-085 3.74798495e-091]
  [7.13222113e-154 8.21798016e-072 5.40223320e-062]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
m=np.zeros((5,5))
for i in range(len(m)):
    if(i<4):
        m[i+1][i] = i+1    
print(m)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
cb = np.zeros((8, 8))
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
print(cb)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
nm     = np.empty((5,5))
nm_max = nm.max()
nm_min = nm.min()
nm     = (nm - nm_min)/(nm_max - nm_min)

print(nm)

[[0.   0.   0.   0.   0.  ]
 [0.25 0.   0.   0.   0.  ]
 [0.   0.5  0.   0.   0.  ]
 [0.   0.   0.75 0.   0.  ]
 [0.   0.   0.   1.   0.  ]]


# 5.  How to find common values between two arrays?

In [5]:
arr1 = np.array([10, 50, 60, 100, 120])
arr2 = np.array([20, 60, 120])

print("Common values in two arrays:")
print(np.intersect1d(arr1, arr2))

Common values in two arrays:
[ 60 120]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday : ",yesterday)

today     = np.datetime64('today', 'D')
print("Today     : ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow  : ",tomorrow)


Yestraday :  2020-07-27
Today     :  2020-07-28
Tomorrow  :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.randint(0,10,6)
b = np.random.randint(0,10,6)

print(a)
print(b)
print(np.equal(a,b))

if(np.allclose(a,b)):
    print("Arrays are equal")
else:
    print("Arrays are not equal")


[6 7 8 8 9 3]
[9 4 3 9 2 7]
[False False False False False False]
Arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
v = np.random.randint(100, size=10)
print("Original array:")
print(v)

v[v.argmax()] = 0
print("Maximum value replaced by 0:")

print(v)

Original array:
[ 7 15 91  9  1 68 45 74  9 29]
Maximum value replaced by 0:
[ 7 15  0  9  1 68 45 74  9 29]


# 9. How to print all the values of an array?

In [9]:
a = np.random.randint(100, size=10) 

for x in range(len(a)): 
    print(a[x], end=' ') 

79 52 14 12 3 58 40 62 85 82 

# 10.Subtract the mean of each row of a matrix

In [10]:
mpx = np.random.randint(10, size=(5,5))
print(mpx)
print()
mpy = mpx - mpx.mean(axis = 1)
print(mpy)

[[4 6 9 4 7]
 [9 2 5 5 6]
 [1 6 5 8 2]
 [8 5 1 1 6]
 [7 4 3 2 1]]

[[-2.   0.6  4.6 -0.2  3.6]
 [ 3.  -3.4  0.6  0.8  2.6]
 [-5.   0.6  0.6  3.8 -1.4]
 [ 2.  -0.4 -3.4 -3.2  2.6]
 [ 1.  -1.4 -1.4 -2.2 -2.4]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
m0 = np.random.randint(10, size=10)

print(m0)

m1 = np.random.choice(range(len(m0)), 5, replace=False)

print(m1)

np.add.at(m0, m1, 1)

print(m0)

[6 4 7 6 0 9 2 2 0 4]
[2 0 9 4 6]
[7 4 8 6 1 9 3 2 0 5]


# 12.How to get the diagonal of a dot product?

In [12]:
mat1 = np.array([[12,7,3], [4 ,5,6], [7 ,8,9]])

mat2 = np.array([[5,8,1], [6,7,3], [4,5,9]])

print(np.diagonal(mat1.dot(mat2)))


[114  97 112]


# 13.How to find the most frequent value in an array?

In [13]:
x = np.random.randint(20, size=20)
print("Original array:")
print(x)
print("\nMost frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[14  0 12 13  9  8 12  5  9  6  6 17 19  1 18 10 19  8 12 17]

Most frequent value in the above array:
12


# 14.How to get the n largest values of an array

In [14]:
x = np.random.randint(20, size=20)
print("Original array:")
print(x)

print("\nLargest value in the above array:")
print(np.max(x))

Original array:
[13  0  8 18  1 11 11 17 11 10  5  1 13 19  6  1 10  1 16 16]

Largest value in the above array:
19


# 15.How to create a record array from a regular array?

In [15]:
arr1 = np.array([("Alex", 26, "New York"), ("Ayisha", 28, "London"), ("Lily", 27, "Paris")])
print("Original arrays:")
print(arr1)
print("\nRecord array;")
result = np.core.records.fromarrays(arr1,names='Names, Age, Place')
print(result, "\n")

print("Names : ", result.Names)

print("\nAge : ", result.Age)

print("\nPlace : ", result.Place)

Original arrays:
[['Alex' '26' 'New York']
 ['Ayisha' '28' 'London']
 ['Lily' '27' 'Paris']]

Record array;
[('Alex', 'Ayisha', 'Lily') ('26', '28', '27')
 ('New York', 'London', 'Paris')] 

Names :  ['Alex' '26' 'New York']

Age :  ['Ayisha' '28' 'London']

Place :  ['Lily' '27' 'Paris']
