# Day 14, 15 - Assignment

# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
m_3D = np.empty((3,3,3))
print(m_3D)

[[[5.18072296e-318 1.10926141e-311 3.91948539e-312]
  [0.00000000e+000 5.34270732e-318 3.91948539e-312]
  [1.10926627e-311 1.10926627e-311 6.95186623e-310]]

 [[6.95186623e-310 0.00000000e+000 1.10926173e-311]
  [3.95252517e-323 6.95186462e-310 2.02369289e-320]
  [3.95252517e-323 6.95186462e-310 9.88131292e-324]]

 [[6.95186462e-310 6.95186462e-310 1.61895431e-319]
  [0.00000000e+000             nan 0.00000000e+000]
  [8.34433679e-308 2.29179042e-312 0.00000000e+000]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
m=np.zeros((5,5))
for i in range(len(m)):
    if(i<4):
        m[i+1][i] = i+1    
print(m)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
cb = np.zeros((8, 8))
cb[1::2, ::2] = 1
cb[::2, 1::2] = 1
print(cb)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
nm     = np.empty((5,5))
nm_max = nm.max()
nm_min = nm.min()
nm     = (nm - nm_min)/(nm_max - nm_min)

print(nm)

[[0.   0.   0.   0.   0.  ]
 [0.25 0.   0.   0.   0.  ]
 [0.   0.5  0.   0.   0.  ]
 [0.   0.   0.75 0.   0.  ]
 [0.   0.   0.   1.   0.  ]]


# 5.  How to find common values between two arrays?

In [5]:
arr1 = np.array([10, 50, 60, 100, 120])
arr2 = np.array([20, 60, 120])

print("Common values in two arrays:")
print(np.intersect1d(arr1, arr2))

Common values in two arrays:
[ 60 120]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday : ",yesterday)

today     = np.datetime64('today', 'D')
print("Today     : ",today)

tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow  : ",tomorrow)


Yestraday :  2020-07-27
Today     :  2020-07-28
Tomorrow  :  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
a = np.random.randint(0,10,6)
b = np.random.randint(0,10,6)

print(a)
print(b)
print(np.equal(a,b))

if(np.allclose(a,b)):
    print("Arrays are equal")
else:
    print("Arrays are not equal")


[6 9 9 2 8 8]
[7 6 2 2 3 0]
[False False False  True False False]
Arrays are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [8]:
v = np.random.randint(100, size=10)
print("Original array:")
print(v)

v[v.argmax()] = 0
print("Maximum value replaced by 0:")

print(v)

Original array:
[65 46 42 44 94 36 21 20 55 93]
Maximum value replaced by 0:
[65 46 42 44  0 36 21 20 55 93]


# 9. How to print all the values of an array?

In [9]:
a = np.random.randint(100, size=10) 

for x in range(len(a)): 
    print(a[x], end=' ') 

47 6 30 24 41 13 93 72 4 47 

# 10.Subtract the mean of each row of a matrix

In [10]:
mpx = np.random.randint(10, size=(5,5))
print(mpx)
print()
mpy = mpx - mpx.mean(axis = 1)
print(mpy)

[[8 6 4 9 1]
 [1 6 8 1 0]
 [0 3 4 9 4]
 [4 3 6 7 5]
 [8 4 9 6 0]]

[[ 2.4  2.8  0.   4.  -4.4]
 [-4.6  2.8  4.  -4.  -5.4]
 [-5.6 -0.2  0.   4.  -1.4]
 [-1.6 -0.2  2.   2.  -0.4]
 [ 2.4  0.8  5.   1.  -5.4]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [11]:
m0 = np.random.randint(10, size=10)

print(m0)

m1 = np.random.choice(range(len(m0)), 5, replace=False)

print(m1)

np.add.at(m0, m1, 1)

print(m0)

[2 5 4 2 5 0 5 0 2 2]
[2 4 6 8 3]
[2 5 5 3 6 0 6 0 3 2]


# 12.How to get the diagonal of a dot product?

In [12]:
mat1 = np.array([[12,7,3], [4 ,5,6], [7 ,8,9]])

mat2 = np.array([[5,8,1], [6,7,3], [4,5,9]])

print(np.diagonal(mat1.dot(mat2)))


[114  97 112]


# 13.How to find the most frequent value in an array?

In [13]:
x = np.random.randint(20, size=20)
print("Original array:")
print(x)
print("\nMost frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[11 13 11  7  3 13  2  7  7 14  8 16  4  3 10 15  7  1  5  2]

Most frequent value in the above array:
7


# 14.How to get the n largest values of an array

In [14]:
x = np.random.randint(20, size=20)
print("Original array:")
print(x)

print("\nLargest value in the above array:")
print(np.max(x))

Original array:
[ 5 13 11 19  1  6  0 14 17 16  2 10  9 17 10  0 10  0  4 13]

Largest value in the above array:
19


# 15.How to create a record array from a regular array?

In [17]:
arr1 = np.array([("Alex", 26, "New York"), ("Ayisha", 28, "London"), ("Lily", 27, "Paris")])
print("Original arrays:")
print(arr1)
print("\nRecord array;")
result = np.core.records.fromarrays(arr1,names='st1, st2, st3')
print(result, "\n")

print("Student 1 : ", result.st1)

print("\nStudent 2 : ", result.st2)

print("\nStudent 3 : ", result.st3)

Original arrays:
[['Alex' '26' 'New York']
 ['Ayisha' '28' 'London']
 ['Lily' '27' 'Paris']]

Record array;
[('Alex', 'Ayisha', 'Lily') ('26', '28', '27')
 ('New York', 'London', 'Paris')] 

Student 1 :  ['Alex' '26' 'New York']

Student 2 :  ['Ayisha' '28' 'London']

Student 3 :  ['Lily' '27' 'Paris']
